// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Persistence;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MyApp.Infrastructure.Persistence.Migrations.SqlServer
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Entities.BillingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("account_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("NVARCHAR2(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("period_start");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)")
                        .HasColumnName("provider");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageUnit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("usage_unit");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_br_account_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_br_correlation_id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_br_provider");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_br_status");

                    b.HasIndex("PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_br_period");

                    b.HasIndex("AccountId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_br_account_period");

                    b.ToTable("billing_records", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.BillingRecord", b =>
                {
                    b.OwnsOne("MyApp.Domain.ValueObjects.MoneyAmount", "Cost", b1 =>
                        {
                            b1.Property<Guid>("BillingRecordId")
                                .HasColumnType("RAW(16)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("DECIMAL(18,8)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("NVARCHAR2(3)")
                                .HasColumnName("cost_currency");

                            b1.HasKey("BillingRecordId");

                            b1.ToTable("billing_records");

                            b1.WithOwner()
                                .HasForeignKey("BillingRecordId");
                        });

                    b.OwnsOne("MyApp.Domain.ValueObjects.MoneyAmount", "UsageQuantity", b1 =>
                        {
                            b1.Property<Guid>("BillingRecordId")
                                .HasColumnType("RAW(16)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("DECIMAL(18,8)")
                                .HasColumnName("usage_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("NVARCHAR2(3)")
                                .HasColumnName("usage_currency");

                            b1.HasKey("BillingRecordId");

                            b1.ToTable("billing_records");

                            b1.WithOwner()
                                .HasForeignKey("BillingRecordId");
                        });

                    b.OwnsOne("MyApp.Domain.ValueObjects.ServiceIdentifier", "Service", b1 =>
                        {
                            b1.Property<Guid>("BillingRecordId")
                                .HasColumnType("RAW(16)");

                            b1.Property<string>("ProviderName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("NVARCHAR2(64)")
                                .HasColumnName("svc_provider");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("NVARCHAR2(64)")
                                .HasColumnName("svc_region");

                            b1.Property<string>("ServiceName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("NVARCHAR2(256)")
                                .HasColumnName("svc_name");

                            b1.HasKey("BillingRecordId");

                            b1.ToTable("billing_records");

                            b1.WithOwner()
                                .HasForeignKey("BillingRecordId");
                        });

                    b.Navigation("Cost")
                        .IsRequired();

                    b.Navigation("Service")
                        .IsRequired();

                    b.Navigation("UsageQuantity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
